apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ../../base
  - ingest-auth.yaml
patches:
  - path: storage.yaml
  - path: demo-env.yaml
# TENANCY:patches

# TENANCY:patches:end
