apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
spec:
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
spec:
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
spec:
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyroscope-data
spec:
  resources:
    requests:
      storage: 2Gi
