apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      containers:
        - name: prometheus
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              memory: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  template:
    spec:
      containers:
        - name: loki
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  template:
    spec:
      containers:
        - name: tempo
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope
spec:
  template:
    spec:
      containers:
        - name: pyroscope
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              memory: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
spec:
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
spec:
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
spec:
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyroscope-data
spec:
  resources:
    requests:
      storage: 50Gi
